* Toppar stream file generated by
* CHARMM General Force Field (CGenFF) program version 1.0.0
* For use with CGenFF version 3.0.1
*

read rtf card append
* Topologies generated by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*
36 1

! "penalty" is the highest penalty score of the associated parameters.
! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

RESI AAA            0.000 ! param penalty= 151.500 ; charge penalty=  53.317
GROUP            ! CHARGE   CH_PENALTY
ATOM C1     CG321  -0.180 !    0.000
ATOM C2     CG311  -0.090 !    0.000
ATOM C3     CG311  -0.090 !    0.000
ATOM C4     CG321  -0.179 !    0.000
ATOM C5     CG321  -0.179 !    0.000
ATOM C6     CG311  -0.088 !    0.000
ATOM C7     CG321  -0.179 !    0.000
ATOM C8     CG311  -0.088 !    0.000
ATOM C9     CG321  -0.179 !    0.000
ATOM C10    CG311   0.020 !    0.570
ATOM C11    CG2O1   0.513 !   27.298
ATOM C12    CG3C51  0.197 !   41.927
ATOM O      OG2D1  -0.494 !   14.908
ATOM N1     NG3C51 -0.618 !   53.317
ATOM C13    CG3C52  0.118 !   32.106
ATOM C14    CG3C52 -0.220 !   14.392
ATOM C15    CG3C52 -0.220 !   16.646
ATOM C16    CG321  -0.060 !   49.445
ATOM C17    CG3C51 -0.113 !   25.944
ATOM C18    CG3C52 -0.176 !   13.102
ATOM C19    CG3C52 -0.178 !    0.000
ATOM C20    CG3C52 -0.178 !    0.000
ATOM C21    CG3C52 -0.176 !   13.102
ATOM N2     NG2S1  -0.447 !   13.295
ATOM H1     HGA2    0.090 !    0.000
ATOM H2     HGA2    0.090 !    0.000
ATOM H3     HGA1    0.090 !    0.000
ATOM H4     HGA1    0.090 !    0.000
ATOM H5     HGA2    0.090 !    0.000
ATOM H6     HGA2    0.090 !    0.000
ATOM H7     HGA2    0.090 !    0.000
ATOM H8     HGA2    0.090 !    0.000
ATOM H9     HGA1    0.090 !    0.000
ATOM H10    HGA2    0.090 !    0.000
ATOM H11    HGA2    0.090 !    0.000
ATOM H12    HGA1    0.090 !    0.000
ATOM H13    HGA2    0.090 !    0.000
ATOM H14    HGA2    0.090 !    0.000
ATOM H15    HGA1    0.090 !    0.000
ATOM H16    HGA1    0.090 !    1.773
ATOM H17    HGA2    0.090 !    1.550
ATOM H18    HGA2    0.090 !    1.550
ATOM H19    HGA2    0.090 !    0.000
ATOM H20    HGA2    0.090 !    0.000
ATOM H21    HGA2    0.090 !    0.200
ATOM H22    HGA2    0.090 !    0.200
ATOM H23    HGA2    0.090 !    3.539
ATOM H24    HGA2    0.090 !    3.539
ATOM H25    HGA1    0.090 !    1.725
ATOM H26    HGA2    0.090 !    0.000
ATOM H27    HGA2    0.090 !    0.000
ATOM H28    HGA2    0.090 !    0.000
ATOM H29    HGA2    0.090 !    0.000
ATOM H30    HGA2    0.090 !    0.000
ATOM H31    HGA2    0.090 !    0.000
ATOM H32    HGA2    0.090 !    0.000
ATOM H33    HGA2    0.090 !    0.000
ATOM H34    HGP1    0.314 !    0.000

BOND H20  C14 
BOND H22  C15 
BOND H18  C13 
BOND C14  C15 
BOND C14  C13 
BOND C14  H19 
BOND C15  H21 
BOND C15  C12 
BOND C13  H17 
BOND C13  N1  
BOND H16  C12 
BOND H24  C16 
BOND C12  N1  
BOND C12  C11 
BOND H25  C17 
BOND N1   C16 
BOND H33  C21 
BOND C16  C17 
BOND C16  H23 
BOND C17  C21 
BOND C17  C18 
BOND O    C11 
BOND C11  N2  
BOND C21  H32 
BOND C21  C20 
BOND H30  C20 
BOND C20  C19 
BOND C20  H31 
BOND H27  C18 
BOND H34  N2  
BOND C18  C19 
BOND C18  H26 
BOND H28  C19 
BOND N2   C10 
BOND H14  C9  
BOND C19  H29 
BOND H12  C8  
BOND H13  C9  
BOND C9   C8  
BOND C9   C2  
BOND C8   C10 
BOND C8   C7  
BOND C10  H15 
BOND C10  C6  
BOND H5   C4  
BOND H3   C2  
BOND C4   C2  
BOND C4   C6  
BOND C4   H6  
BOND C2   C1  
BOND H9   C6  
BOND C6   C5  
BOND C7   H10 
BOND C7   H11 
BOND C7   C3  
BOND C1   H1  
BOND C1   C3  
BOND C1   H2  
BOND C5   C3  
BOND C5   H7  
BOND C5   H8  
BOND C3   H4  
IMPR C11    C12    N2     O     

END

read param card flex append
* Parameters generated by analogy by
* CHARMM General Force Field (CGenFF) program version 1.0.0
*

! Penalties lower than 10 indicate the analogy is fair; penalties between 10
! and 50 mean some basic validation is recommended; penalties higher than
! 50 indicate poor analogy and mandate extensive validation/optimization.

BONDS
CG2O1  CG3C51  250.00     1.4900 ! PROT 6-31g* AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG2O1  NG2S1   370.00     1.3450 ! PROT Alanine Dipeptide ab initio calc's (LK)
CG2O1  OG2D1   620.00     1.2300 ! PROT Peptide geometry, condensed phase (LK)
CG311  CG311   222.50     1.5000 ! PROT alkane update, adm jr., 3/2/92
CG311  CG321   222.50     1.5380 ! PROT alkane update, adm jr., 3/2/92
CG311  NG2S1   320.00     1.4300 ! PROT NMA Gas & Liquid Phase IR Spectra (LK)
CG311  HGA1    309.00     1.1110 ! PROT alkane update, adm jr., 3/2/92
CG321  CG3C51  222.50     1.5280 ! TF2M, viv
CG321  NG3C51  263.00     1.4740 ! drug.p , from CG321 NG311, PENALTY= 20
CG321  HGA2    309.00     1.1110 ! PROT alkane update, adm jr., 3/2/92
CG3C51 CG3C52  195.00     1.5180 ! THF, nucleotide CSD/NDB survey, 5/30/06,viv
CG3C51 NG3C51  400.00     1.4780 ! drug.p , from CG3C52 NG3C51, PENALTY= 4
CG3C51 HGA1    307.00     1.1000 ! THF, THF neutron diffr., 5/30/06, viv
CG3C52 CG3C52  195.00     1.5300 ! THF, nucleotide CSD/NDB survey, 5/30/06,viv; increased to 1.53 by kevo
CG3C52 NG3C51  400.00     1.4780 ! PRLD, pyrrolidine; 2PRL, 2-pyrroline, kevo
CG3C52 HGA2    307.00     1.1000 ! THF, THF neutron diffr., 5/30/06, viv
NG2S1  HGP1    440.00     0.9970 ! PROT Alanine Dipeptide ab initio calc's (LK)

ANGLES
CG3C51 CG2O1  NG2S1    80.00    116.50 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG3C51 CG2O1  OG2D1    80.00    118.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
NG2S1  CG2O1  OG2D1    80.00    122.50 ! PROT NMA Vib Modes (LK)
CG311  CG311  CG311    53.35    111.00    8.00   2.56100 ! PROT alkane update, adm jr., 3/2/92
CG311  CG311  CG321    53.35    111.00    8.00   2.56100 ! PROT alkane update, adm jr., 3/2/92
CG311  CG311  NG2S1    70.00    113.50 ! PROT Alanine Dipeptide ab initio calc's (LK)
CG311  CG311  HGA1     34.50    110.10   22.53   2.17900 ! PROT alkane update, adm jr., 3/2/92
CG321  CG311  CG321    58.35    113.50   11.16   2.56100 ! LIPID glycerol
CG321  CG311  HGA1     34.50    110.10   22.53   2.17900 ! PROT alkane update, adm jr., 3/2/92
NG2S1  CG311  HGA1     48.00    108.00 ! PROT Alanine Dipeptide ab initio calc's (LK)
CG311  CG321  CG311    58.35    113.50   11.16   2.56100 ! PROT alkanes
CG311  CG321  HGA2     33.43    110.10   22.53   2.17900 ! PROT alkanes
CG3C51 CG321  NG3C51   43.70    112.20 ! drug.p , from CG331 CG321 NG311, PENALTY= 13.9
CG3C51 CG321  HGA2     34.60    110.10   22.53   2.17900 ! TF2M viv
NG3C51 CG321  HGA2     32.40    109.50   50.00   2.13000 ! drug.p , from NG311 CG321 HGA2, PENALTY= 3
HGA2   CG321  HGA2     35.50    109.00    5.40   1.80200 ! PROT alkane update, adm jr., 3/2/92
CG2O1  CG3C51 CG3C52   52.00    112.30 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG2O1  CG3C51 NG3C51   52.00    112.30 ! drug.p , from CG2O1 CG3C51 CG3C52, PENALTY= 42
CG2O1  CG3C51 HGA1     50.00    112.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG321  CG3C51 CG3C52   58.00    115.00    8.00   2.56100 ! TF2M viv
CG321  CG3C51 HGA1     34.60    110.10   22.53   2.17900 ! TF2M viv
CG3C52 CG3C51 CG3C52   58.00    109.50   11.16   2.56100 ! THF, nucleotide CSD/NDB survey, 05/30/06, viv
CG3C52 CG3C51 NG3C51   84.00    107.60 ! drug.p , from CG3C52 CG3C52 NG3C51, PENALTY= 4
CG3C52 CG3C51 HGA1     35.00    111.40   22.53   2.17900 ! TF2M, viv
NG3C51 CG3C51 HGA1     54.00    109.00 ! drug.p , from NG3C51 CG3C52 HGA2, PENALTY= 4
CG3C51 CG3C52 CG3C52   58.00    109.50   11.16   2.56100 ! THF, nucleotide CSD/NDB survey, 05/30/06, viv
CG3C51 CG3C52 HGA2     35.00    111.40   22.53   2.17900 ! TF2M, viv
CG3C52 CG3C52 CG3C52   58.00    109.50   11.16   2.56100 ! THF, nucleotide CSD/NDB survey, 05/30/06, viv
CG3C52 CG3C52 NG3C51   84.00    107.60 !x 107 PRLD, pyrrolidine; 103.3 2PRL, 2-pyrroline; 100.4 2IMI, 2-imidazoline; 2PRZ, 2-pyrazoline, kevo
CG3C52 CG3C52 HGA2     35.00    111.40   22.53   2.17900 ! TF2M, viv
NG3C51 CG3C52 HGA2     54.00    109.00 !v 107.7 PRLD, pyrrolidine; 110.8 2PRL, 2-pyrroline; 110.4 3PRL, 3-pyrroline; 111.4 2IMI, 2-imidazoline; 111.7 2PRZ, 2-pyrazoline, kevo
HGA2   CG3C52 HGA2     38.50    106.80    5.40   1.80200 ! THF, 10/17/05 viv
CG2O1  NG2S1  CG311    50.00    120.00 ! PROT NMA Vib Modes (LK)
CG2O1  NG2S1  HGP1     34.00    123.00 ! PROT NMA Vib Modes (LK)
CG311  NG2S1  HGP1     35.00    117.00 ! PROT NMA Vibrational Modes (LK)
CG321  NG3C51 CG3C51   47.00    103.90 ! drug.p , from CG3C52 NG3C51 NG3P2, PENALTY= 48.9
CG321  NG3C51 CG3C52   47.00    103.90 ! drug.p , from CG3C52 NG3C51 NG3P2, PENALTY= 48.5
CG3C51 NG3C51 CG3C52  140.00    103.70 ! drug.p , from CG3C52 NG3C51 CG3C52, PENALTY= 0.4

DIHEDRALS
NG2S1  CG2O1  CG3C51 CG3C52     0.4000  1     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
NG2S1  CG2O1  CG3C51 CG3C52     0.6000  2     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
NG2S1  CG2O1  CG3C51 NG3C51     0.4000  1     0.00 ! drug.p , from NG2S1 CG2O1 CG3C51 CG3C52, PENALTY= 42
NG2S1  CG2O1  CG3C51 NG3C51     0.6000  2     0.00 ! drug.p , from NG2S1 CG2O1 CG3C51 CG3C52, PENALTY= 42
NG2S1  CG2O1  CG3C51 HGA1       0.4000  1   180.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
NG2S1  CG2O1  CG3C51 HGA1       0.6000  2     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
OG2D1  CG2O1  CG3C51 CG3C52     0.4000  1   180.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
OG2D1  CG2O1  CG3C51 CG3C52     0.6000  2     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
OG2D1  CG2O1  CG3C51 NG3C51     0.4000  1   180.00 ! drug.p , from OG2D1 CG2O1 CG3C51 CG3C52, PENALTY= 42
OG2D1  CG2O1  CG3C51 NG3C51     0.6000  2     0.00 ! drug.p , from OG2D1 CG2O1 CG3C51 CG3C52, PENALTY= 42
OG2D1  CG2O1  CG3C51 HGA1       0.4000  1     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
OG2D1  CG2O1  CG3C51 HGA1       0.6000  2     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG3C51 CG2O1  NG2S1  CG311      1.6000  1     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG3C51 CG2O1  NG2S1  CG311      2.5000  2   180.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG3C51 CG2O1  NG2S1  HGP1       2.5000  2   180.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
OG2D1  CG2O1  NG2S1  CG311      2.5000  2   180.00 ! PROT Gives appropriate NMA cis/trans barrier. (LK)
OG2D1  CG2O1  NG2S1  HGP1       2.5000  2   180.00 ! PROT Gives appropriate NMA cis/trans barrier. (LK)
CG311  CG311  CG311  CG321      0.5000  4   180.00 ! NA bkb
CG311  CG311  CG311  HGA1       0.1950  3     0.00 ! NA, sugar
CG321  CG311  CG311  NG2S1      0.2000  3     0.00 ! PROT alkane update, adm jr., 3/2/92
CG321  CG311  CG311  HGA1       0.1950  3     0.00 ! NA, sugar
NG2S1  CG311  CG311  HGA1       0.2000  3     0.00 ! PROT alkane update, adm jr., 3/2/92
HGA1   CG311  CG311  HGA1       0.1950  3     0.00 ! NA, sugar
CG311  CG311  CG321  CG311      0.2000  3     0.00 ! CA, Cholic Acid, reset to default by kevo
CG311  CG311  CG321  HGA2       0.1950  3     0.00 ! NA, sugar
CG321  CG311  CG321  CG311      0.2000  3     0.00 ! PROT alkane update, adm jr., 3/2/92
CG321  CG311  CG321  HGA2       0.1950  1     0.00 ! NA, sugar
HGA1   CG311  CG321  CG311      0.1950  3     0.00 ! NA, sugar
HGA1   CG311  CG321  HGA2       0.1950  3     0.00 ! NA, sugar
CG311  CG311  NG2S1  CG2O1      1.8000  1     0.00 ! PROT ala dipeptide, new C VDW Rmin, adm jr., 3/3/93c
CG311  CG311  NG2S1  HGP1       0.0000  1     0.00 ! PROT Alanine Dipeptide ab initio calc's (LK)
HGA1   CG311  NG2S1  CG2O1      0.0000  1     0.00 ! PROT Alanine Dipeptide ab initio calc's (LK)
HGA1   CG311  NG2S1  HGP1       0.0000  1     0.00 ! PROT Alanine Dipeptide ab initio calc's (LK)
NG3C51 CG321  CG3C51 CG3C52     0.2000  3   180.00 ! drug.p , from OG301 CG321 CG3C51 CG3C52, PENALTY= 33
NG3C51 CG321  CG3C51 HGA1       0.1950  3     0.00 ! drug.p , from OG301 CG321 CG3C51 HGA1, PENALTY= 33
HGA2   CG321  CG3C51 CG3C52     0.1600  3     0.00 ! alkane, 4/98, yin and mackerell, tf2m viv
HGA2   CG321  CG3C51 HGA1       0.1600  3     0.00 ! alkane, 4/98, yin and mackerell, tf2m viv
CG3C51 CG321  NG3C51 CG3C51     0.4000  1     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
CG3C51 CG321  NG3C51 CG3C51     0.2500  2     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
CG3C51 CG321  NG3C51 CG3C51     0.6000  3     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
CG3C51 CG321  NG3C51 CG3C52     0.4000  1     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
CG3C51 CG321  NG3C51 CG3C52     0.2500  2     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
CG3C51 CG321  NG3C51 CG3C52     0.6000  3     0.00 ! drug.p , from CG321 CG324 NG3P2 CG324, PENALTY= 151.5
HGA2   CG321  NG3C51 CG3C51     0.0000  3   180.00 ! drug.p , from HGA2 CG321 NG311 CG2R61, PENALTY= 113.5
HGA2   CG321  NG3C51 CG3C52     0.0000  3   180.00 ! drug.p , from HGA2 CG321 NG311 CG2R61, PENALTY= 113.5
CG2O1  CG3C51 CG3C52 CG3C52     0.1400  3     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG2O1  CG3C51 CG3C52 HGA2       0.1400  3     0.00 ! PROT AcProNH2, ProNH2, AcProNHCH3 RLD 4/23/93
CG321  CG3C51 CG3C52 CG3C52     0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
CG321  CG3C51 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
CG3C52 CG3C51 CG3C52 CG3C52     0.4100  3   180.00 ! cpen, cyclopentane, viv 10/4/05
CG3C52 CG3C51 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
NG3C51 CG3C51 CG3C52 CG3C52     0.6900  3     0.00 ! drug.p , from CG3C52 CG3C52 CG3C52 NG3C51, PENALTY= 4
NG3C51 CG3C51 CG3C52 HGA2       0.0000  3     0.00 ! drug.p , from NG3C51 CG3C52 CG3C52 HGA2, PENALTY= 4
HGA1   CG3C51 CG3C52 CG3C52     0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
HGA1   CG3C51 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
CG2O1  CG3C51 NG3C51 CG321      2.0500  3   180.00 ! drug.p , from CG2R51 CG3C52 NG3C51 CG3C52, PENALTY= 81.5
CG2O1  CG3C51 NG3C51 CG3C52     2.0500  3   180.00 ! drug.p , from CG2R51 CG3C52 NG3C51 CG3C52, PENALTY= 50.5
CG3C52 CG3C51 NG3C51 CG321      0.1800  3     0.00 ! drug.p , from CG3C52 CG3C52 NG3C51 CG3C52, PENALTY= 35
CG3C52 CG3C51 NG3C51 CG3C52     0.1800  3     0.00 ! drug.p , from CG3C52 CG3C52 NG3C51 CG3C52, PENALTY= 4
HGA1   CG3C51 NG3C51 CG321      0.0000  3     0.00 ! drug.p , from HGA2 CG3C52 NG3C51 CG3C52, PENALTY= 35
HGA1   CG3C51 NG3C51 CG3C52     0.0000  3     0.00 ! drug.p , from HGA2 CG3C52 NG3C51 CG3C52, PENALTY= 4
CG3C51 CG3C52 CG3C52 CG3C52     0.4100  3   180.00 ! cpen, cyclopentane, viv 10/4/05
CG3C51 CG3C52 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
CG3C52 CG3C52 CG3C52 CG3C52     0.4100  3   180.00 ! cpen, cyclopentane, viv 10/4/05
CG3C52 CG3C52 CG3C52 NG3C51     0.6900  3     0.00 ! PRLD, pyrrolidine fit_dihedral run 31, kevo
CG3C52 CG3C52 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
NG3C51 CG3C52 CG3C52 HGA2       0.0000  3     0.00 ! 2PRL, 2-pyrroline; 2IMI, 2-imidazoline, kevo
HGA2   CG3C52 CG3C52 HGA2       0.1900  3     0.00 ! alkane, 4/98, yin and mackerell, thf, viv
CG3C52 CG3C52 NG3C51 CG321      0.1800  3     0.00 ! drug.p , from CG3C52 CG3C52 NG3C51 CG3C52, PENALTY= 31
CG3C52 CG3C52 NG3C51 CG3C51     0.1800  3     0.00 ! drug.p , from CG3C52 CG3C52 NG3C51 CG3C52, PENALTY= 0.4
HGA2   CG3C52 NG3C51 CG321      0.0000  3     0.00 ! drug.p , from HGA2 CG3C52 NG3C51 CG3C52, PENALTY= 31
HGA2   CG3C52 NG3C51 CG3C51     0.0000  3     0.00 ! drug.p , from HGA2 CG3C52 NG3C51 CG3C52, PENALTY= 0.4

IMPROPERS
CG2O1  CG3C51 NG2S1  OG2D1    120.0000  0     0.00 ! PROT NMA Vibrational Modes (LK) WILDCARD

END
RETURN
